"""Read numeric binary-profile contracts from the owning C header."""
from pathlib import Path
import re
_source=Path(__file__).resolve().parents[2]/"src/twospace_fixture.h"
VALUES={name:int(number,0) for name,number in re.findall(
    r"^#define (TSF_[A-Z_]+) (0x[0-9a-fA-F]+|[0-9]+)U?\s*$",_source.read_text(),re.M)}
CORE=VALUES["TSF_CORE_BYTES"];REAL=VALUES["TSF_REAL_BYTES"]
KPOOL=VALUES["TSF_KPOOL_REAL"];UPOOL=VALUES["TSF_UPOOL_REAL"]
KBYTES=VALUES["TSF_KPOOL_BYTES"];UBYTES=VALUES["TSF_UPOOL_BYTES"]
SERVICE=VALUES["TSF_SERVICE_REAL"];SERVICE_BYTES=VALUES["TSF_SERVICE_BYTES"]
SERVICE_PAGES=VALUES["TSF_SERVICE_PAGES"]
STACK=VALUES["TSF_KSTACK_EXT_REAL"];STACK_BYTES=VALUES["TSF_KSTACK_EXT_BYTES"]
STACK_PAGES=VALUES["TSF_KSTACK_PAGES"];TRAMPOLINE=VALUES["TSF_TRAMPOLINE_VA"]
if (REAL!=0x20000000 or CORE!=0x1000000 or SERVICE_BYTES!=SERVICE_PAGES*4096 or
    STACK_BYTES!=(STACK_PAGES-4)*4096 or KPOOL+KBYTES>UPOOL or UPOOL+UBYTES>CORE or
    SERVICE+SERVICE_BYTES>STACK or STACK+STACK_BYTES>KPOOL or TRAMPOLINE<0x02000000+SERVICE_BYTES):
    raise ValueError("reviewed workstation profile layout")
