         L     R15,=A(LOOKSWA)    GET TOKEN CONVERSION
         BALR  R14,R15            INVOKE IT
         LTR   R6,R15             LOAD AND TEST ADDRESS
         BNP   OPSERR               NO JFCB ?
*COMP*   AIF   ('&ZSYS' NE 'S390').MVSJFCB
*COMP*   XC    DDWSWA(DDWSWAL),DDWSWA  CLEAR SWA LIST FORM
*COMP*   LA    R1,DDWSVA          ADDRESS OF JFCB TOKEN
*COMP*   ST    R1,DDWEPA
*COMP*   MVC   DDWSVA+4(3),TIOEJFCB    JFCB TOKEN
*COMP*   SWAREQ FCODE=RL,EPA=DDWEPA,MF=(E,DDWSWA),UNAUTH=YES
*COMP*   BXH   R15,R15,OPSERR
*COMP*   ICM   R6,15,DDWSVA       LOAD JFCB ADDRESS
*COMP*   BZ    OPSERR               NO; SERIOUS PROBLEM
*COMP*   AGO   .COMJFCB
*MVSJFCB SR    R6,R6              FOR AM31
*COMP*   ICM   R6,7,TIOEJFCB      SHOULD NEVER BE ZERO
*COMP*   BZ    OPSERR               NO; SERIOUS PROBLEM
*COMP*   LA    R6,16(,R6)         SKIP QUEUE HEADER
.COMJFCB MVC   MYJFCB(JFCBLGTH),0(R6)   MOVE TO MY STORAGE
         OI    DDWFLAG2,CWFDD     DD FOUND
